name: speech-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - mlflow
    - tensorflow==2.0.0
    - librosa
    - matplotlib
    - scikit-learn
    - scipy
    - seaborn
    - simpleaudio